// generated by stringer -type=Op -output=op_stringer.go; DO NOT EDIT

package fsnotify

import "fmt"

const (
	_Op_name_0 = "CreateWrite"
	_Op_name_1 = "Remove"
	_Op_name_2 = "Rename"
	_Op_name_3 = "Chmod"
)

var (
	_Op_index_0 = [...]uint8{6, 11}
	_Op_index_1 = [...]uint8{6}
	_Op_index_2 = [...]uint8{6}
	_Op_index_3 = [...]uint8{5}
)

func (i Op) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		lo := uint8(0)
		if i > 0 {
			lo = _Op_index_0[i-1]
		}
		return _Op_name_0[lo:_Op_index_0[i]]
	case i == 4:
		return _Op_name_1
	case i == 8:
		return _Op_name_2
	case i == 16:
		return _Op_name_3
	default:
		return fmt.Sprintf("Op(%d)", i)
	}
}
